### ISSUE TITLE
TypeError: 'DataContainer' object is not subscriptable

### ISSUE THREAD

**Issue by pawopawo** [Meituan-AutoML/Twins#26]
```
Traceback (most recent call last):
  File "train.py", line 202, in <module>
    main()
  File "train.py", line 198, in main
    meta=meta)
  File "/opt/tiger/conda/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/tiger/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/tiger/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/opt/tiger/conda/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 308, in call_hook
    getattr(hook, fn_name)(self)
  File "/opt/tiger/conda/lib/python3.7/site-packages/mmdet/core/evaluation/eval_hooks.py", line 276, in after_train_epoch
    gpu_collect=self.gpu_collect)
  File "/opt/tiger/conda/lib/python3.7/site-packages/mmdet/apis/test.py", line 97, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/opt/tiger/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tiger/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/opt/tiger/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tiger/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/opt/tiger/conda/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 183, in forward
    return self.:(img, img_metas, **kwargs)
  File "/opt/tiger/conda/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 150, in forward_test
    img_meta[img_id]['batch_input_shape'] = tuple(img.size()[-2:])
TypeError: 'DataContainer' object is not subscriptable
```

COCO检测的时候，train没问题，但test一直有上面的bug

**Comment by cxxgtxy** [comment]
看起来是mmdetection的版本问题
